recruit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from interviews import views as interviewsViews
from jobs import views as jobsViews
from candidates import views as candidatesViews
from recruiters import views as recruitersViews
from dashboards import views as dashboardViews
from django.contrib.auth.models import User

urlpatterns = [
    url(r'^$', dashboardViews.dashboards, name='dashboards'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^jobs/$', jobsViews.view_jobs, name='jobs'),
    url(r'^jobs/(?P<job_id>\d+)/$', jobsViews.view_job_details, name='job_details'),
    url(r'^candidates/apply/$', candidatesViews.apply, name='candidate_apply'),
    url(r'^candidates/apply/success/$', candidatesViews.apply_success, name='candidate_apply_success'),    
    url(r'^recruiters/', recruitersViews.view_recruiters, name='recruiters'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}), 
    url(r'^available/(?P<bu_id>\d+)/$', interviewsViews.available, name='available'),
    url(r'^availability/(?P<bu_id>\d+)/$', interviewsViews.availability, name='availability'),
    url(r'^interviews/', interviewsViews.interview_requests, name='interviews')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

candidates/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django_countries.fields import CountryField

from jobs.models import Job
from recruit.choices import (EDUCATION_CHOICES, EMPLOYER_TYPE_CHOICES)

class Candidate(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	birth_year = models.CharField(max_length=4, blank=False)
	date_of_birth = models.DateField(blank=True, null=True)
	gender = models.CharField(choices=(('male', 'Male'), ('female', 'Female'),), max_length = 10, blank=True, null=True)
	education = models.CharField(
			max_length=25,
			blank=True,
			choices=EDUCATION_CHOICES,
		)	
	education_major = models.CharField(max_length=250, blank=True)
	current_location = CountryField(blank=True)
	image = models.ImageField(upload_to='employer/%Y/%m/%d')
	thumb = models.ImageField(upload_to='employer/%Y/%m/%d', blank=True)
	is_active = models.BooleanField(default=True)
	last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)

	def save(self, *args, **kwargs):
		from recruit.utils import generate_thumbnail
		self.thumb = generate_thumbnail(self.image)
		super(Candidate, self).save(*args, **kwargs)

	def delete(self, *args, **kwargs):
		from recruit.utils import delete_from_s3
		delete_from_s3([self.image, self.thumb])
		super(Candidate, self).delete(*args, **kwargs)	


	def __str__(self):
		return self.user.email

def update_user_profile(sender, instance, created, **kwargs):
	from accounts.models import UserProfile
	if created:
		UserProfile.objects.filter(user=instance.user).update(user_type='Candidate')

post_save.connect(update_user_profile, sender=Candidate)		

class CandidateRequirements(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	# location = models.ManyToManyField(Location, on_delete=models.CASCADE)  create m2m
	employer_type = models.CharField(
			max_length=25,
			blank=True,
			choices=EMPLOYER_TYPE_CHOICES,
		)

class CandidateDocument(models.Model):
	candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
	document = models.FileField(upload_to='candidate/%Y/%m/%d')	
	document_type = models.CharField(max_length=50)
	is_active = models.BooleanField(default=1)
	last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)

	def delete(self, *args, **kwargs):
		from recruit.utils import delete_from_s3
		delete_from_s3([self.document])
		super(CandidateDocument, self).delete(*args, **kwargs)

dashboards/models.py
from django.db import models

# Create your models here.

candidates/forms.py
from django import forms
from django_countries.fields import LazyTypedChoiceField
from django_countries import countries
from recruit.choices import (TIMEZONE_CHOICES, EDUCATION_CHOICES,
	 GENDER_CHOICES)

class UserApplyStep1Form(forms.Form):
	first_name = forms.CharField(max_length=20)
	last_name = forms.CharField(max_length=20)
	email = forms.EmailField(max_length=50)
	citizenship = LazyTypedChoiceField(choices=countries)
	skype_id = forms.CharField(label='Skype ID', max_length=20)
	timezone = forms.ChoiceField(choices=TIMEZONE_CHOICES)

class UserApplyStep2Form(forms.Form):
	birth_year = forms.IntegerField(min_value=1950, max_value=2000)
	gender = forms.TypedChoiceField(choices=GENDER_CHOICES)
	education = forms.TypedChoiceField(choices=EDUCATION_CHOICES)
	education_major = forms.CharField(max_length=50)
	image = forms.ImageField()
	resume = forms.FileField()

candidates/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect
from accounts.models import UserProfile

from .models import Candidate, CandidateDocument
from .forms import UserApplyStep1Form, UserApplyStep2Form

def apply(request):

	key = request.GET.get('key', None)
	user = UserProfile.verify_token(key)

	if not key and request.method == 'POST':
		
		form = UserApplyStep1Form(request.POST)

		if form.is_valid():
			data = form.data
			first_name = data['first_name']
			last_name = data['last_name']
			email = data['email']
			citizenship = data['citizenship']
			skype_id = data['skype_id']
			timezone = data['timezone']

			user, created = User.objects.get_or_create(
				first_name=first_name,
				last_name=last_name,
				email=email,
				username=email
				)

			if not created:
				messages.add_message(request, messages.ERROR,
					email + ' has already been registered.')
			else:
				userprofile = UserProfile(
					user=user,
					timezone=timezone,
					citizenship=citizenship,
					skype_id=skype_id,
					user_type='Candidate'
					)

				userprofile.save()
				
				key = user.userprofile.generate_token()
				
				return HttpResponseRedirect(
					reverse('candidate_apply') + '?key=' + key)


	elif not key and request.method == 'GET':
		form = UserApplyStep1Form()

	elif key and user and request.method == 'POST':

		form = UserApplyStep2Form(request.POST, request.FILES)
	
		if form.is_valid():
			files = form.files
			data = form.data
	
			try:
				candidate = user.candidate
				candidate.birth_year = data['birth_year']
				candidate.gender = data['gender']
				candidate.education = data['education']
				candidate.education_major = data['education_major']
				candidate.image = files['image']
				candidate.save()
			except Candidate.DoesNotExist:
				candidate = Candidate.objects.create(user=user, 
					birth_year=data['birth_year'],
					gender=data['gender'],
					education=data['education'],
					education_major=data['education_major'],
					image=files['image']
					)
			CandidateDocument.objects.create(
				candidate=candidate,
				document=files['resume'],
				document_type='Resume'
				)

			messages.add_message(request, messages.SUCCESS,
				'Form submitted successfully.')

			return HttpResponseRedirect(
					reverse('candidate_apply_success') + '?key=' + key)

	elif key and user and request.method == 'GET':
		form = UserApplyStep2Form()

	else:
		messages.add_message(request, messages.ERROR,
			'A valid application key is required to submit documents. ' +
			'Please contact the administrator.')
		form = None

	return render(request, 'candidates/apply.html', {'form': form})

def apply_success(request):
	key = request.GET.get('key', None)
	user = UserProfile.verify_token(key)

	if not key or not user:
		messages.add_message(request, messages.ERROR,
			'A valid application key is required to view this page.')
	else:
		jobs_url = reverse('jobs') + '?key=' + key
		availability_url = reverse('available', args=[user.id]) + '?key=' + key

	return render(request, 'candidates/apply.html', 
			{'success': 'success',
			 'jobs_url': jobs_url,
			 'availability_url': availability_url
			})

dashboards/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from interviews.models import InterviewInvitation, InterviewRequest
from jobs.models import Job

@login_required
def dashboards(request):
	if request.user.is_authenticated:

		user_type = request.user.userprofile.user_type

		if user_type == 'Candidate':
			return render(request, 'candidates/dashboard.html')

		if user_type == 'Recruiter':

			interviews_pending_confirmation =\
				InterviewInvitation.objects.exclude(
					confirmed_time__isnull=False,
				).count()

			interviews_pending_follow_up =\
				InterviewInvitation.objects.exclude(
					confirmed_time__isnull=True,
					result='',
				).count()

			pending_employer_requests =\
				InterviewRequest.objects.filter(
					employer_accepted=True,
					candidate_accepted__isnull=True,
				).count()

			pending_candidate_requests =\
				InterviewRequest.objects.filter(
					candidate_accepted=True,
					employer_accepted__isnull=True,
				).count()
				
			context = {
				'interviews_pending_confirmation': interviews_pending_confirmation,
				'interviews_pending_follow_up': interviews_pending_follow_up,
				'pending_employer_requests': pending_employer_requests,
				'pending_candidate_requests': pending_candidate_requests,
			}

			return render(request, 'recruiters/dashboard.html',
				context)

		if user_type == 'Employer':
			return render(request, 'employers/dashboard.html')	

	return render(request, 'home.html')	

candidates/templates/candidates/_progress.html
<div class="row bs-wizard" style="border-bottom:0;">
    
    <div id="step1" class="col-xs-3 bs-wizard-step">
      <div class="text-center bs-wizard-stepnum">Step 1</div>
      <div class="progress"><div class="progress-bar"></div></div>
      <a href="#" class="bs-wizard-dot"></a>
      <div class="bs-wizard-info text-center">Basic Information</div>
    </div>
    
    <div id="step2" class="col-xs-3 bs-wizard-step"><!-- complete -->
      <div class="text-center bs-wizard-stepnum">Step 2</div>
      <div class="progress"><div class="progress-bar"></div></div>
      <a href="#" class="bs-wizard-dot"></a>
      <div class="bs-wizard-info text-center">Resume</div>
    </div>
    
    <div id="step3" class="col-xs-3 bs-wizard-step"><!-- complete -->
      <div class="text-center bs-wizard-stepnum">Step 3</div>
      <div class="progress"><div class="progress-bar"></div></div>
      <a href="#" class="bs-wizard-dot"></a>
      <div class="bs-wizard-info text-center">Submit!</div>
    </div>
</div>

candidates/templates/candidates/_progress_style.html
<style>
.bs-wizard {margin-top: 40px;}

/*Form Wizard*/
.bs-wizard {border-bottom: solid 1px #e0e0e0; padding: 0 0 10px 0;}
.bs-wizard > .bs-wizard-step {padding: 0; position: relative;}
.bs-wizard > .bs-wizard-step + .bs-wizard-step {}
.bs-wizard > .bs-wizard-step .bs-wizard-stepnum {color: #595959; font-size: 16px; margin-bottom: 5px;}
.bs-wizard > .bs-wizard-step .bs-wizard-info {color: #999; font-size: 14px;}
.bs-wizard > .bs-wizard-step > .bs-wizard-dot {position: absolute; width: 30px; height: 30px; display: block; background: #fbe8aa; top: 45px; left: 50%; margin-top: -15px; margin-left: -15px; border-radius: 50%;} 
.bs-wizard > .bs-wizard-step > .bs-wizard-dot:after {content: ' '; width: 14px; height: 14px; background: #fbbd19; border-radius: 50px; position: absolute; top: 8px; left: 8px; } 
.bs-wizard > .bs-wizard-step > .progress {position: relative; border-radius: 0px; height: 8px; box-shadow: none; margin: 20px 0;}
.bs-wizard > .bs-wizard-step > .progress > .progress-bar {width:0px; box-shadow: none; background: #fbe8aa;}
.bs-wizard > .bs-wizard-step.complete > .progress > .progress-bar {width:100%;}
.bs-wizard > .bs-wizard-step.active > .progress > .progress-bar {width:50%;}
.bs-wizard > .bs-wizard-step:first-child.active > .progress > .progress-bar {width:0%;}
.bs-wizard > .bs-wizard-step:last-child.active > .progress > .progress-bar {width: 100%;}
.bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot {background-color: #f5f5f5;}
.bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot:after {opacity: 0;}
.bs-wizard > .bs-wizard-step:first-child  > .progress {left: 50%; width: 50%;}
.bs-wizard > .bs-wizard-step:last-child  > .progress {width: 50%;}
.bs-wizard > .bs-wizard-step.disabled a.bs-wizard-dot{ pointer-events: none; }
/*END Form Wizard*/	
</style>

candidates/templates/candidates/apply.html
{% extends 'base.html' %}

{% block head %}
{{ block.super }}

{% include 'candidates/_progress_style.html' %}

{% endblock %}

{% block content %}

{% if form %}
{% include 'candidates/_progress.html' %}
<h1>Application Page</h1>
<form method='post' enctype="multipart/form-data">
{% csrf_token %}
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.label_tag }} {{ field }}
        {{ field.errors }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}
<input type='submit' value='Submit'>
</form>
{% endif %}

{% if success %}
<h1>Congratulations! <small>Application Submitted</small></h1>
<div class='row'>
    <div class='col-md-offset-3 col-md-6'>
        <h3>What next?</h3>
        <p>Your application materials have been received and our being reviewed. To speed
        up the job search please request interviews for jobs of interest and provide your
        interview time availability below.
        <ul>
            <li>
                <a href='{{ jobs_url }}'>
                    Request job interviews
                </a>
            </li>
            <li>
                <a href='{{ availability_url }}'>
                    Provide your interview availability
                </a>
            </li>
        </ul>
    </div>
</div>
{% endif %}

{% endblock %}

{% block scripts %}
{{ block.super }}
<script>
    $('#step1').addClass('complete');
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.6/jstz.min.js"></script>
<script>
	var timezoneValues = Object.values(jstz.olson.timezones);
	var detectedTimezone = jstz.determine().name();
	if(timezoneValues.indexOf(detectedTimezone) != -1) {
	  $('#id_timezone').prop('selected', true).val(detectedTimezone);
	}
</script>
{% endblock %}

candidates/templates/candidates/dashboard.html
{% extends "base.html" %}
<div class='row'>
	<div class='col-xs-12 col-sm-6'>
		<h2>Overview</h2>
		<ul class="list-group">
			<li class="list-group-item">
				<a href='#'><span class="badge">18</span>
					Interviews Pending Confirmation
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'><span class="badge">15</span>
					Interviews Awaiting Follow Up
				</a>
			</li>			
			<li class="list-group-item">
				<a href='#'><span class="badge">14</span>
					New Jobs
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'><span class="badge">20</span>
					...
				</a>
			</li>
		</ul>
	</div>
	<div class='col-xs-12 col-sm-6'>
		<h2>Actions</h2>
		<ul class="list-group">
			<li class="list-group-item">
				<a href='#'>
					Update Preferences
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'>
					Update Resume
				</a>
			</li>			
			<li class="list-group-item">
				<a href='#'>
					Update Availability
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'>
					...
				</a>
			</li>
		</ul>		
	</div>
</div>